### ISSUE TITLE
Remove numpy from `mnist.py`

### ISSUE THREAD

**Issue by yrmo** [yrmo/cudagrad#48]

**Comment by yrmo** [comment]
Oh MNIST is `.npz` can't remove it completely...

**Comment by yrmo** [comment]
Equality should return `Tensor`:
```py
>>> from cudagrad import Tensor
>>> Tensor([1], [4.2])
<Tensor([1, ], [4.2, ]) object at 0x6079c8d74c40 DefaultBackward>
>>> t = Tensor([1], [4.2])
>>> t
<Tensor([1, ], [4.2, ]) object at 0x6079c8d766a0 DefaultBackward>
>>> t == t
True
>>> import numpy as np
>>> a = np.array([4.2])
>>> a == a
array([ True])
```
bd6619858e6558ba305a20518b4aef20f8f4b684

**Comment by yrmo** [comment]
Add `==` to [Tensor.ipynb](https://github.com/yrmo/cudagrad/blob/main/Tensor.ipynb)

**Comment by yrmo** [comment]
```py
>>> import numpy as np
>>> np.array([1,2])
array([1, 2])
>>> a = np.array([1,2])
>>> a
array([1, 2])
>>> b = np.array([1,2])
>>> a == b
array([ True,  True])
>>> bool(a == b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by yrmo** [comment]
```py
>>> from torch import tensor
>>> tensor([1])
tensor([1])
>>> t = tensor([4.2])
>>> t
tensor([4.2000])
>>> t == t
tensor([True])
```

**Comment by yrmo** [comment]
```py
>>> a = torch.arange(5)
>>> b = 2
>>> print(b == a) 
tensor([False, False,  True, False, False])
>>> print(torch.eq(b, a))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: eq() received an invalid combination of arguments - got (int, Tensor), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Number other, *, Tensor out)
```
https://discuss.pytorch.org/t/torch-eq-vs-equality-operator/147847/4
