### ISSUE TITLE
Allow `slice` to be passed to `__getitem__` `__setitem__` (at least `[:]`)

### ISSUE THREAD

**Issue by yrmo** [yrmo/cudagrad#59]
Needed for https://github.com/yrmo/cudagrad/issues/25 to speed up SGD

```py
>>> class SliceViewer:
...     def __getitem__(self, x):
...             if isinstance(x, slice):
...                     print(x.start, x.stop, x.step)
...             else:
...                     print(x)
... 
>>> 
>>> SliceViewer()[:]
None None None
>>> SliceViewer()[0]
0
>>> from cudagrad import Tensor
>>> t = Tensor([1], [4.2])
>>> t
<Tensor([1, ], [4.2, ]) object at 0x5ce19f206b00 DefaultBackward>
>>> t.data()
[4.199999809265137]
>>> t[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'cudagrad.tensor.Tensor' object is not subscriptable
>>> t[[0]]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'cudagrad.tensor.Tensor' object is not subscriptable
>>> t.data[[0]]
<Tensor([1, ], [4.2, ]) object at 0x5ce19f3be970 SelectBackward>
>>> t.data[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: cudagrad.tensor._DataProxy, arg0: list[int]) -> cg::Tensor

Invoked with: <cudagrad.tensor._DataProxy object at 0x74a4e0bdfeb0>, 0
>>> t.data
<cudagrad.tensor._DataProxy object at 0x74a4e09f4c30>
>>> t.data()
[4.199999809265137]
>>> t.data[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: cudagrad.tensor._DataProxy, arg0: list[int]) -> cg::Tensor

Invoked with: <cudagrad.tensor._DataProxy object at 0x74a4e09f4c30>, 0
>>> t.data[[0]]
<Tensor([1, ], [4.2, ]) object at 0x5ce19f3be970 SelectBackward>
>>> t.data[:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: cudagrad.tensor._DataProxy, arg0: list[int]) -> cg::Tensor

Invoked with: <cudagrad.tensor._DataProxy object at 0x74a4e0bdfeb0>, slice(None, None, None)
>>> t.data[[:]]
  File "<stdin>", line 1
    t.data[[:]]
            ^
SyntaxError: invalid syntax
>>> l = [0, 1, 2]
>>> l[:]
[0, 1, 2]
```

https://numpy.org/doc/stable/user/basics.indexing.html
https://github.com/python/cpython/blob/main/Objects/listobject.c
https://stackoverflow.com/questions/2936863/implementing-slicing-in-getitem

**Comment by yrmo** [comment]
https://github.com/numpy/numpy/blob/7bff2754f64cb855c39b59cf6d0b7bc51fe49a61/numpy/_core/src/multiarray/mapping.c#L254

**Comment by yrmo** [comment]
https://github.com/yrmo/SliceViewer

**Comment by yrmo** [comment]
Test CMakeLists don't have pybind11 https://github.com/yrmo/cudagrad/issues/11
