### ISSUE TITLE
Fix `!pip install cudagrad` on kaggle.com (add PyPI 'Built Distribution')

### ISSUE THREAD

**Issue by yrmo** [yrmo/cudagrad#72]
Accelerator: None
```py
Collecting cudagrad
  Downloading cudagrad-0.1.0.tar.gz (785 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 785.5/785.5 kB 9.6 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cudagrad
  Building wheel for cudagrad (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cudagrad (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-310/cudagrad
      copying cudagrad/__init__.py -> build/lib.linux-x86_64-cpython-310/cudagrad
      copying cudagrad/linear.py -> build/lib.linux-x86_64-cpython-310/cudagrad
      copying cudagrad/nn.py -> build/lib.linux-x86_64-cpython-310/cudagrad
      copying cudagrad/mlp.py -> build/lib.linux-x86_64-cpython-310/cudagrad
      copying cudagrad/moons.py -> build/lib.linux-x86_64-cpython-310/cudagrad
      running egg_info
      writing cudagrad.egg-info/PKG-INFO
      writing dependency_links to cudagrad.egg-info/dependency_links.txt
      writing top-level names to cudagrad.egg-info/top_level.txt
      reading manifest file 'cudagrad.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'cudagrad.egg-info/SOURCES.txt'
      running build_ext
      cmake: /opt/conda/lib/libcurl.so.4: no version information available (required by cmake)
      cmake: /opt/conda/lib/libcurl.so.4: no version information available (required by cmake)
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at /usr/share/cmake-3.16/Modules/FindCUDA.cmake:707 (message):
        Specify CUDA_TOOLKIT_ROOT_DIR
      Call Stack (most recent call first):
        CMakeLists.txt:4 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-mzpag6eh/cudagrad_a843dd339e424819b058fdc9e5c6a0a8/build/temp.linux-x86_64-cpython-310/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 54, in <module>
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-l6qtzt7d/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "<string>", line 26, in run
        File "<string>", line 39, in build_extension
        File "/opt/conda/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-mzpag6eh/cudagrad_a843dd339e424819b058fdc9e5c6a0a8', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-mzpag6eh/cudagrad_a843dd339e424819b058fdc9e5c6a0a8/build/lib.linux-x86_64-cpython-310', '-DPYTHON_EXECUTABLE=/opt/conda/bin/python3.10']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cudagrad
Failed to build cudagrad
ERROR: Could not build wheels for cudagrad, which is required to install pyproject.toml-based projects
```

**Comment by yrmo** [comment]
#78
