### ISSUE TITLE
Cannot build manylinux wheel for PyPI

### ISSUE THREAD

**Issue by yrmo** [yrmo/cudagrad#78]
4e0ca7f78cf002eab73f713ac8612cc0830f3285

```py
ryan@Lambda-TensorBook:~/cudagrad/dist$ auditwheel repair cudagrad-0.2.4-cp310-cp310-linux_x86_64.whl 
INFO:auditwheel.main_repair:Repairing cudagrad-0.2.4-cp310-cp310-linux_x86_64.whl
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "cudagrad-0.2.4-cp310-cp310-linux_x86_64.whl" to "manylinux_2_5_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
```

https://github.com/pypa/manylinux
https://github.com/mayeut/pep600_compliance

**Comment by yrmo** [comment]
[.ci/manywheel/build_common.sh](https://github.com/pytorch/pytorch/blob/main/.ci/manywheel/build_common.sh)

**Comment by yrmo** [comment]
```
ryan@Lambda-TensorBook:~$ docker run -it --entrypoint /bin/bash gcr.io/kaggle-images/python
root@dd70ea8b98d5:/# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by yrmo** [comment]
```
ryan@Lambda-TensorBook:~$ docker run -it --entrypoint /bin/bash  gcr.io/kaggle-images/python
root@330d0894aee5:/# python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

**Comment by yrmo** [comment]
f068f77329409fd2feccce84232b94f7a2a5a032
```
root@d7bd9d98dc7d:/cudagrad# python
Python 3.10.14 (main, Nov  8 2024, 04:48:54) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudagrad
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cudagrad/cudagrad/__init__.py", line 1, in <module>
    from cudagrad.nn import Module as Module
  File "/cudagrad/cudagrad/nn.py", line 12, in <module>
    from cudagrad.tensor import Tensor
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /cudagrad/cudagrad/tensor.so)
```

**Comment by yrmo** [comment]
```
docker build . -t manylinux-ubuntu
docker rm manylinux-container
docker run -it --name manylinux-container manylinux-ubuntu python -c "import time; time.sleep(10)" &
docker cp manylinux-container:/cudagrad/dist/cudagrad-0.2.4-cp310-cp310-linux_x86_64.whl ~/cudagrad/dist/
mv ~/cudagrad/dist/cudagrad-0.2.4-cp310-cp310-linux_x86_64.whl ~/cudagrad/dist/cudagrad-0.2.4-cp310-cp310-manylinux2014_x86_64.whl 
```

**Comment by yrmo** [comment]
<img width="926" alt="image" src="https://github.com/user-attachments/assets/26667610-c0f7-4d83-b3a6-ecdc12c4c08f">
